### ISSUE TITLE
tweaks not working

### ISSUE THREAD

**Issue by amthius** [slugbyte/lackluster.nvim#35]
Hey, really cool color scheme! However, it seems overriding the tweaks does not work at all for me.

`NVIM v0.10.0`
`Windows 11`

![image](https://github.com/slugbyte/lackluster.nvim/assets/51867420/4fc5e2c4-3b80-4562-8104-481338e1b288)

**Comment by slugbyte** [comment]
glad you like the scheme :) sorry bout the bug, I patch it asap!

**Comment by slugbyte** [comment]
Just took a look and the  main branch seems to be working for me, try updating your plugin, this is probbly due to a patch I merged yesterday to fix typos everywhere in my codebase, #33, it changed `tweek_syntax` -> `tweak_syntax`  and I made a patch that makes  lackluster backwards compatable #34, but if you have an old version it wont know what `tweak_syntax` is... let me know if that fixes your bug :)

**Comment by amthius** [comment]
Yep, that solved the problem! Silly me for not updating..

**Comment by slugbyte** [comment]
sweet! glad that worked :)
