### ISSUE TITLE
suggestion: open up the API for customisation

### ISSUE THREAD

**Issue by sebszyller** [slugbyte/lackluster.nvim#51]
### Did you read the docs?

- [X] I have read the docs.

### What would you like to change?

The API should expose all highlight groups for customisation. Currently, `tweak_syntax` has very limited options.

### Why do you think this will improve lackluster?

Currently, you can change the highlights manually via the lua API which isn't ideal. All big modern themes allow for customisation from within the setup.

**Comment by slugbyte** [comment]
@sebszyller Thanks for the suggestion!

I get that it's pretty common for modern colorschemes to have quite a bit of flexibility, however I think that I want to keep lacklusters tweek-ablity and codebase more or less minimal, if people want to go as far as to tweak all their highlights I think it's probably best to use `nvim_set_hl`. and along with `lackluster.colors` or there own colors. nvim_set_hl has lots of features that my internal implementation does not support on purpose, because I wanted to keep things simple and minimal. Mostly I kinda just want to keep lackluster plug and play, as much as possible.

If there are any specific tweaks that you think are critical, I would be open to considering adding support. Do you have any specific features that you think many people would want to tweak which are not yet supported?

Also I'm on holiday for the next two weeks, and I might be slow at responding. I do try to check Github notifications every few days.

**Comment by sebszyller** [comment]
Yeah, I get that and I usually don't change much.
As of now, most things in markdown default to `text`. And the default `Visual` is meh.

Any particular why you think that overriding highlight groups in the config would make it less *plug and play*?

**Comment by slugbyte** [comment]
As I see things, there is no supposed to for highlights it's all a matter of choice and preference. I intentionally disabled the todo_comments bg, and I happen to like the way I set the diagnostics and visual highlights. If that's not your thing that's totally ok. I’m sure there may be need for loads of improvements to all kinds of highlights, but your feedback doesn’t make any points that I find actionable.

Also I suppose you're right that it would not be less plug and play if did add the proposed feature, because no one would have to use it. That said still I don't think adding this feature fits my goals for this project, at this point in time. I also think that other projects having support for this feature is not enough of a reason for me to add it. So until I decide otherwise the best strategy for you would be to use `nvim_set_hl`, sorry that isn’t what you were looking for.

Side note: I don't know if you intend it or not, but your last comment came off as pretty rude by both expressing your preference as a fact and a judgement, and by stating you’ve done no research to check what I have or haven’t done and  then stating you assume that my work is not correct. If you want people to help you or work for you for free, you probably should try to be more considerate and thoughtful with your feedback. I am going give you the benefit of the doubt, that this was just a miscommunication. 

Anyway, Since I don’t plan on adding this feature Im closing the ticket. All the best to you!
