### ISSUE TITLE
proposal: support for mini.nvim plugin

### ISSUE THREAD

**Issue by mosaab2020** [slugbyte/lackluster.nvim#62]
### Did you read the Contributing Guide?

- [X] I have read the Contributing Guide

### Description

i wanna add support for mini-starter, and maybe on other mini.nvim plugins
it will take some time.

**Comment by slugbyte** [comment]
Sounds great! Thanks a lot :) 
Let me know if you have any questions :)

**Comment by mosaab2020** [comment]
Hello, i am trying to to support mini.jump, it doesn't work.

`spec.fg("MiniJump", color.black),   
spec.bg("MiniJump", color.gray8) `

**Comment by slugbyte** [comment]
sorry the spec.* funcs are a bit confussing, i should write better docs :)

* `spec.co( fg_color, bg_color)`

Each highlight can only be assigned once, so the issue above is that you essentially assingned `MiniJump` twice so would be overwritten with bg as gray8 and fg wolud be un assigned


use spec.co if you want to assign fg bg and optionaly options (like bold, itallic ...)
`spec.co(name, fg, bg, options)`

the following only allow you to set one thing at a time
`spec.fg(name, fg)`
`spec.bg(name, bg)`
`spec.op(name, options)`
`spec.ln(name, link_to_name)`

**Comment by slugbyte** [comment]
let me know it that works for you :)

**Comment by slugbyte** [comment]
heck yee! Glad that helped! Lemme know if you have any other questions :)

Also feel free to open a PR for each plugin you finish, if you want :) also don't worry about adding any plugin_disable stuff... right now all the mini stuff is under one plugin_disable flag, but I might make each mini plugin have their own disable flag after there are a few more implemented :)

**Comment by mosaab2020** [comment]
mini.jump2d is know working!
i will make a pull request for mini.jump and mini.jump2d :) 

![Screenshot_2024-08-29_07-27-58](https://github.com/user-attachments/assets/85aa6562-1116-4746-8ffd-291a38ba6812)

**Comment by mosaab2020** [comment]
question: after adding mini.jump and mini.jump2d support, is there any other thing that i need to do because in the open request it asks for an example plugin config?

**Comment by slugbyte** [comment]
naw your all good, dont worry about the example config, just open the pr :)

**Comment by slugbyte** [comment]
merged #63 !! Thanks so much!

**Comment by slugbyte** [comment]
do you have plans to try to add support for more mini plugins? No pressure, just curious if we should keep this ticket open

**Comment by mosaab2020** [comment]
i want to add other plugins

**Comment by mosaab2020** [comment]
from my testing, i found that [mini-indentscope.md](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-indentscope.md) works out of the box so you can remove these plugins from the [CONTRIBUTING.md](https://github.com/slugbyte/lackluster.nvim/blob/main/CONTRIBUTING.md):

> mini-jump
mini-jump2d
mini-indentscope.md

**Comment by slugbyte** [comment]
added them to the README and removed them from CONTRIBUTING :)

**Comment by mosaab2020** [comment]
mini.starter doesn't need any setup, it works out of the box.

![Screenshot_2024-09-01_12-29-24](https://github.com/user-attachments/assets/2bde911b-dc72-4892-8c75-d3bddaf627cc)

**Comment by slugbyte** [comment]
If possible I would want to change the orange to gray5 or gray6

**Comment by mosaab2020** [comment]
Ok boss

**Comment by mosaab2020** [comment]
### mini.starter works by typing the first letters of a file, then opening it.
#### there are two colors:
##### MiniStarterItemPrefix: which is the first letters of a file or option, like here:
The fg color is color.gray6 and the bg is color is color.none
![Screenshot_2024-09-02_21-28-47](https://github.com/user-attachments/assets/dcccdbf0-30aa-445b-8d73-7961130f63fb)

##### MiniStarterQuery: which is the first letter you type like if i wanna open ehllo-world.js i will type the letter "e" and the letter "e" will be highlighted in color.blue like this:
I tried color.lack, but i found that it is hard to see
![Screenshot_2024-09-02_21-29-17](https://github.com/user-attachments/assets/02ea2624-e013-4808-b30e-ffae1cd50a29)


### If you want to change anything tell me so i can make a pull request

**Comment by slugbyte** [comment]
Heck yee, Looks great @mosaab2020! Feel free to Open a PR :)

**Comment by mosaab2020** [comment]
I opened a PR :)

**Comment by slugbyte** [comment]
MERGED :) Thanks dude!

**Comment by slugbyte** [comment]
I just openend a Issue with mini.starter to try an add a new highlight group so that the `'(mini.starter)'` text in the logs will not have to be orange :) [link to issue](https://github.com/echasnovski/mini.nvim/issues/1196)

**Comment by mosaab2020** [comment]
Nice! i hope they add support soon :)

**Comment by mosaab2020** [comment]
I am now working at [mini-statusline](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-statusline.md).

**Comment by mosaab2020** [comment]
All the colors are the same as lualine

![Screenshot_2024-09-04_21-49-33](https://github.com/user-attachments/assets/cfa83b9b-c43d-455b-88dc-744aff3da35a)

What do you think?

**Comment by slugbyte** [comment]
Your killin it! Thanks soo much!

Is there support for different colors for insert, visual, command,replace mode, and out of focus in mini.statusline?

with lualine I have these colors for the different modes
command, insert -> bg is lack, fg is gray7 
visual,replace -> bg gray9, fg is black
out of focus (if relevent) bg is gray1, fg is gray4
[lackluster luline](https://github.com/slugbyte/lackluster.nvim/blob/main/lua/lualine/themes/lackluster.lua)

I'ma go ahead and say you should always feel free to open PRs when every you want, I can help you tweek and debug faster if I can see the diff :)

**Comment by mosaab2020** [comment]
yes there is support for different colors, all the colors i used are the same fg and bg for every mode (insert, visual, command, replace mode, and out of focus)
take a look:

![Screenshot_2024-09-05_05-34-32](https://github.com/user-attachments/assets/5090adc9-634b-4557-8cef-a45e3289aa34)

**Comment by mosaab2020** [comment]
> I'ma go ahead and say you should always feel free to open PRs when every you want, I can help you tweek and debug faster if I can see the diff :)

Sounds great!

**Comment by slugbyte** [comment]
Merged!!!

**Comment by mosaab2020** [comment]
i forgot to add mini-statusline to the README.md and remove it from the contributing.md

**Comment by mosaab2020** [comment]
only 5 more plugins to finish! and then maybe i could help adding some features and additional themes for waybar, and "maybe" a vscode theme (if you want of course :)

**Comment by slugbyte** [comment]
@mosaab2020 your a legend! Would absolutely love the help! No pressure though, just do whatever you think is fun :)

**Comment by mosaab2020** [comment]
question: how to do you test the highlights and modifications of the colorscheme.

my current setup is modifying theme then i commit the changes and push it to a fork  of the colorschemes, after all that i update the colorscheme using lazy and then i can test it.

is there an better way to test highlights? 
i know that this question is not related to the issue but it can help me test and improve the colorscheme faster.

**Comment by slugbyte** [comment]
Oh yead, I've totally been there. I feel like I struggled with this same thing for years tinkering with different neovim stuff. I have a better workflow now but I'm sure it could still be improved upon.

Here are a few tips:

## strat 1 (lazy.nvim)
I use lazy.nvim and do these 3 things 
1. set my `dev path` when i call the `lazy.setup()` function [heres a link to how i do this](https://github.com/slugbyte/config/blob/21e24daecf2977ed08d8f68df7f50ba2b92dc028/config/nvim/lua/slugbyte/lazy.lua#L50) 
2.   I put put all the neovim plugins that I develop in that directory (the dev path dir).
3. when i load a lazy plugin i set "dev = true" [example using lackluster](https://github.com/slugbyte/config/blob/21e24daecf2977ed08d8f68df7f50ba2b92dc028/config/nvim/lua/slugbyte/plugin/colorscheme.lua#L4)

when dev is true lazy.nvim will use the local directory instead of requiring you to update the repo and then pull the updates with lazy! this means you can make changes, and just open up vim and they will be allready loaded :)

## strat 2 (plenary.reload) 
you can use plenary.nvim to force reload lua modules (basicly force rerequire)...

```lua
-- you can create a function like this and then just add a keymap for it
function reload_lackluster()
    require("plenary.reload").reload_module("lackluster")
    require("lackluster").setup(your_config)
end 
```
using this strat you can edit lackluster, run your keyboard shortcut and then see your changes in your current session

if strat2 doen't work you might need to add the parrent dir to your vim runtime path `vim.opt.runtimepath:append(",~/path/to/your/dev/dir")`

## strat 3 source file
if your just editing a file that runs some lua code you can run `:source %` to run that file, this isn't super helpful for files that just export/return code

sometimes I like to put files that run setup functions in there own files so that i can just `:source %` them after i make changes... 

for example i have a [dir called lackluster](https://github.com/slugbyte/config/tree/main/config/nvim/lua/slugbyte/lackluster) in my config, that just has stuff I dont usully use but want to keep for testing/development, and those files only get loaded when i comment them back in from my [lackluster_testing.lua](https://github.com/slugbyte/config/blob/main/config/nvim/lua/slugbyte/plugin/lackluster_testing.lua) file

**Comment by slugbyte** [comment]
Hope thats  helpful and not to messy of an explanation :) Let me know if you want me to re-clarify anything or if you have any questions :)

**Comment by slugbyte** [comment]
Also one more tip, I like to use tmux (or you can just use multiple terminal windows) because if you write something with a bug and then load it you can mess up vim sometimes and it can be super annoying (because for example you may have to fix the bug with out any of your keymaps or settings), so when Im tweaking config/plugins I often use a second window for opening up vim to double check that it doesnt spit up a bunch of errors and break things

(this can be the downside of strats 2 and 3 above)

**Comment by mosaab2020** [comment]
thanks so much! that was helpful :)

i don't believe that i just switched to neovim (from vscodium) less one month ago and now i am making little help to a neovim plugin!

i didn't had fun working on something for a long time til i found this project :)

**Comment by slugbyte** [comment]
Thats awesome dude, having fun is whats its all about! Many times when I've been stuck in a programming rut I've gotten unsuck by deciding to mess around and build something for my neovim setup It tends to bring the joy back to coding for me :)

Glad that my suggestions could help!  :)

**Comment by mosaab2020** [comment]
I am know working at [mini-cursorword](https://github.com/echasnovski/mini.nvim/blob/main/readmes/mini-cursorword.md), it puts a line under word that is under the cursor.
there is to ways to theme it:

1. just a line under the word like this ( the line under the word is the same color as the word):
![Screenshot_2024-09-06_15-51-44](https://github.com/user-attachments/assets/3c1c36b4-d12a-461e-8e61-45755cd5563b)

2. highlight the bg of the word
![Screenshot_2024-09-06_15-53-01](https://github.com/user-attachments/assets/5c4df298-b023-4adc-915d-16d3b85ff9c0)

**Comment by slugbyte** [comment]
I like the first version with just the underline.

**Comment by mosaab2020** [comment]
the first version doesn't need any thing. it works out of the box

**Comment by mosaab2020** [comment]
2 plugins left :)

**Comment by slugbyte** [comment]
Wooohooo!

**Comment by mosaab2020** [comment]
hello, i can't work at more plugins, i would like to work at other things (in the colorscheme like help add a theme for waybar or something)

closing the issue

**Comment by slugbyte** [comment]
@mosaab2020 Thanks so much for all the contributions, I really appreciate everything you've done! Feel free to work on other stuff if you want to, but no pressure :)
